In [1]:
import numpy as np
from scipy import linalg


In [2]:
a=np.arange(36).reshape(6,6)
linalg.eig(a.dot(a.T))#特征值，特征向量

(array([  1.48833326e+04 +0.00000000e+00j,
          2.66674146e+01 +0.00000000e+00j,
          5.69898646e-13 +0.00000000e+00j,
         -2.83125331e-14 +6.64401253e-14j,
         -2.83125331e-14 -6.64401253e-14j,  -2.39095770e-14 +0.00000000e+00j]),
 array([[-0.05255297+0.j        ,  0.72183635+0.j        ,
          0.10265574+0.j        , -0.42694537+0.10699567j,
         -0.42694537-0.10699567j, -0.05684334+0.j        ],
        [-0.17270437+0.j        ,  0.51518084+0.j        ,
          0.01618342+0.j        ,  0.06365469-0.32233467j,
          0.06365469+0.32233467j,  0.32981073+0.j        ],
        [-0.29285577+0.j        ,  0.30852533+0.j        ,
          0.10567529+0.j        ,  0.64216882+0.j        ,
          0.64216882-0.j        , -0.43565582+0.j        ],
        [-0.41300717+0.j        ,  0.10186983+0.j        ,
         -0.05975991+0.j        ,  0.04500065+0.23371871j,
          0.04500065-0.23371871j,  0.44634837+0.j        ],
        [-0.53315857+0.j        , -0

In [3]:
m,n=10,10#方针才可以求逆
A=np.random.rand(m,n)
B=np.random.rand(m,1)
x1=linalg.solve(A,B)#solve ax=b,faster
x2=np.dot(linalg.inv(A),B)#x=a-1*b,slower
print(np.allclose(x1,x2))#


True


In [4]:
#lu 分解
luf=linalg.lu_factor(A)
x3=linalg.lu_solve(luf,B)
np.allclose(x1,x3)

True

In [5]:
luf[0]

array([[ 0.96791203,  0.22328524,  0.22441649,  0.85268333,  0.08156653,
         0.15654591,  0.39263851,  0.74840003,  0.4160021 ,  0.89673368],
       [ 0.71274002,  0.81565239,  0.13244489, -0.13611805,  0.03335979,
        -0.02205981,  0.29660569, -0.06011774,  0.02740368, -0.06271686],
       [ 0.1548519 ,  0.07696042,  0.88875507,  0.50727963,  0.14808666,
         0.85607906,  0.32280673,  0.53620415,  0.83388353,  0.40607045],
       [ 0.91143681,  0.19789524,  0.40351257, -0.8500011 ,  0.42087757,
        -0.16766242,  0.40725717, -0.67765161, -0.11579877, -0.90699147],
       [ 0.34355007,  0.76295728, -0.06824961, -0.12938179,  0.92272443,
         0.83295474,  0.28010379,  0.40458711,  0.79175062,  0.57142025],
       [ 0.27570074,  0.88937532,  0.61126261, -0.6654824 ,  0.73068297,
        -0.54494165,  0.39212636, -0.71137199, -1.18506926, -0.89922807],
       [ 0.78815261,  0.44785231,  0.81589208,  0.29025842,  0.04142352,
         0.69887063, -0.92473262,  0.01188001

## 最小二乘法
 ### lstsq,

In [6]:
linalg.lstsq?

## 特征值，eig

In [7]:
evalues,evector=linalg.eig(A)
evalues,evector

(array([ 5.46189026+0.j        , -0.70805556+0.j        ,
        -0.25678862+0.68746567j, -0.25678862-0.68746567j,
         0.13589589+0.77643424j,  0.13589589-0.77643424j,
         0.91813423+0.j        ,  0.54285439+0.j        ,
        -0.17233806+0.10470077j, -0.17233806-0.10470077j]),
 array([[ 0.34243421+0.j        ,  0.28139765+0.j        ,
         -0.19538301+0.09974316j, -0.19538301-0.09974316j,
         -0.05801598+0.06758749j, -0.05801598-0.06758749j,
          0.21226221+0.j        , -0.08404496+0.j        ,
         -0.09476265+0.00199816j, -0.09476265-0.00199816j],
        [ 0.26364799+0.j        ,  0.17663542+0.j        ,
          0.11758111-0.01091384j,  0.11758111+0.01091384j,
          0.18406337-0.23481295j,  0.18406337+0.23481295j,
         -0.07430446+0.j        ,  0.03470520+0.j        ,
         -0.07513548-0.00531059j, -0.07513548+0.00531059j],
        [ 0.30923796+0.j        ,  0.11010866+0.j        ,
          0.06855624-0.03887351j,  0.06855624+0.03887351j

## 奇异值分解，svd ,linalg.svd
#### 提取有用信息，可以按照用无用信息提取


In [ ]:
from scipy.misc import imread
r,g,b=np.rollaxis(imread('CD28.jpg'),2).astype(float)
img=0.2829*r+0.5870*g+0.1140*b
img.shape

(2880, 2912)

In [ ]:
U,s,Vh=linalg.svd(img)
U.shape,s.shape,Vh.shape

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(s,lw=3)
plt.show()

#### 一共有2000个特征，可是只有前边几个有用，后边的效果很不明显。
#### U*s*Vh

In [ ]:
def composite(U,s,Vh,n):
    return np.dot(U[:,:n],s[:n,np.newaxis]*Vh[:n,:])#怎么想乘的呢？


In [ ]:
np.allclose(img,composite(U,s,Vh,len(s)))

In [ ]:
img5=composite(U,s,Vh,5)
img50=composite(U,s,Vh,50)
img100=composite(U,s,Vh,100)
plt.imshow(img)
plt.show()
plt.imshow(img5)
plt.show()
plt.imshow(img50)
plt.show()

In [ ]:
plt.imshow(img100)
plt.show()

In [ ]:
img50.shape       

### 统计-stats

In [ ]:
from scipy.stats import norm


它包含四类常用的函数：

- `norm.cdf` 返回对应的[累计分布函数](https://zh.wikipedia.org/wiki/%E7%B4%AF%E7%A7%AF%E5%88%86%E5%B8%83%E5%87%BD%E6%95%B0)值
- `norm.pdf` 返回对应的[概率密度函数](https://zh.wikipedia.org/wiki/%E6%A9%9F%E7%8E%87%E5%AF%86%E5%BA%A6%E5%87%BD%E6%95%B8)值
- `norm.rvs` 产生指定参数的随机变量
- `norm.fit` 返回给定数据下，各参数的[最大似然估计](https://zh.wikipedia.org/wiki/%E6%9C%80%E5%A4%A7%E4%BC%BC%E7%84%B6%E4%BC%B0%E8%AE%A1)（MLE）值

从正态分布产生500个随机点：

In [ ]:
x=norm.rvs(size=500)
type(x)

In [ ]:
h=plt.hist(x)

In [ ]:
h=plt.hist(x,normed=True,bins=20)

In [ ]:
x_mean,x_std=norm.fit(x)
x_mean,x_std

In [ ]:
h=plt.hist(x,normed=True,bins=20)
xx=np.linspace(-3,3,100)
p=plt.plot(xx,norm.pdf(xx),'r-')

### 不定积分

In [ ]:
from scipy.integrate import trapz

In [ ]:
p=trapz(norm.pdf(xx),xx)
p

In [ ]:
plt.fill_between(xx, norm.pdf(xx), color = 'red')



In [ ]:
x=np.linspace(-5,5,100)
p = plt.plot(x, norm.pdf(x, loc=0, scale=1))
p = plt.plot(x, norm.pdf(x, loc=0.5, scale=2))
p = plt.plot(x, norm.pdf(x, loc=-0.5, scale=.5))

### 其他连续分布

In [ ]:
from scipy.stats import lognorm, t, dweibull
#对数正态分布，t分布，韦氏分布

In [ ]:
 x = np.linspace(0.01, 3, 100)
 
plt.plot(x, dweibull.pdf(x, 1), label='s=1, constant failure rate')
plt.plot(x, dweibull.pdf(x, 2), label='s>1, increasing failure rate')
plt.plot(x, dweibull.pdf(x, .1), label='0<s<1, decreasing failure rate')
plt.legend() 
plt.show()

In [ ]:
x = np.linspace(-3, 3, 100)

plt.plot(x, t.pdf(x, 1), label='df=1')
plt.plot(x, t.pdf(x, 2), label='df=2')
plt.plot(x, t.pdf(x, 100), label='df=100')
plt.plot(x[::5], norm.pdf(x[::5]), 'kx', label='normal')
plt.legend()
plt.show()


### 离散分布

In [ ]:
from scipy.stats import binom, poisson, randint
#二项分布，泊松分布，随机数

In [ ]:
#二项分布
num_trials = 60
x = np.arange(num_trials)

plt.plot(x, binom(num_trials, 0.5).pmf(x), 'o-', label='p=0.5')
plt.plot(x, binom(num_trials, 0.2).pmf(x), 'o-', label='p=0.2')
plt.legend()
plt.show()



### 自定义离散分布
导入函数

In [ ]:
from scipy.stats import rv_discrete
xk=[1,2,3,4,5,6]
pk=[0.3,0.35,0.25,0.05,0.025,0.025]

In [ ]:
loaded=rv_discrete(values=(xk,pk))
loaded.rvs(size=2)

In [ ]:
rv_y=loaded.rvs(size=100)
plt.hist(rv_y)
plt.show()

### 假设检验
