In [1]:
import numpy as np
import torch

## 张量

构建一个 5x3 的矩阵, 未初始化的:

In [2]:
x=torch.Tensor(5,3)
x

tensor(1.00000e-12 *
       [[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  3.2457,  0.0000]])

构建一个随机初始化的矩阵:

In [4]:
y=torch.rand(5,3)
y

tensor([[ 0.0909,  0.0925,  0.8743],
        [ 0.0230,  0.4320,  0.5599],
        [ 0.6565,  0.7331,  0.9744],
        [ 0.0482,  0.4081,  0.8124],
        [ 0.1539,  0.1387,  0.8970]])

获得 size:

In [5]:
x.size()

torch.Size([5, 3])

In [6]:
x.shape

torch.Size([5, 3])

## 操作

#### 两种加法

In [7]:
z=x+y
z

tensor([[ 0.0909,  0.0925,  0.8743],
        [ 0.0230,  0.4320,  0.5599],
        [ 0.6565,  0.7331,  0.9744],
        [ 0.0482,  0.4081,  0.8124],
        [ 0.1539,  0.1387,  0.8970]])

加法: 提供一个输出 tensor 作为参数

In [10]:
result=torch.Tensor(5,3)
torch.add(x,y,out=result)

tensor([[ 0.0909,  0.0925,  0.8743],
        [ 0.0230,  0.4320,  0.5599],
        [ 0.6565,  0.7331,  0.9744],
        [ 0.0482,  0.4081,  0.8124],
        [ 0.1539,  0.1387,  0.8970]])

In [11]:
#add x to y
y.add_(x)

tensor([[ 0.0909,  0.0925,  0.8743],
        [ 0.0230,  0.4320,  0.5599],
        [ 0.6565,  0.7331,  0.9744],
        [ 0.0482,  0.4081,  0.8124],
        [ 0.1539,  0.1387,  0.8970]])

### 转换一个 Torch Tensor 为 NumPy 数组

In [13]:
a=torch.ones(5)
b=a.numpy()
b,a

(array([1., 1., 1., 1., 1.], dtype=float32), tensor([ 1.,  1.,  1.,  1.,  1.]))

In [14]:
a.add_(1)

tensor([ 2.,  2.,  2.,  2.,  2.])

In [15]:
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)

array([2., 2., 2., 2., 2.])

In [18]:
torch.cuda.is_available()

False

### 任何改变张量的操作方法都是以后缀 _ 结尾的. 
    例如: x.copy_(y),  x.t_(), 将改变张量 x.
    改变数组形状用view

In [19]:
x=torch.randn(4,4)
y=x.view(16)

In [20]:
z=x.view(-1,8)
z.shape

torch.Size([2, 8])

转换 NumPy 数组为 Torch Tensor


In [21]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)

[2. 2. 2. 2. 2.]
