In [1]:
%matplotlib inline


Tensors
=======

Tensors 在 PyTorch 中的操作方式 与 Torch 几乎完全相同.

用未初始化的内存创建一个大小为 (5 x 7) 的 tensor:




In [4]:
import torch
a = torch.FloatTensor(5, 7)

In [5]:
a

tensor(1.00000e-38 *
       [[ 0.5786,  0.8449,  0.5327,  0.8908,  1.0286,  0.8908,  0.8908],
        [ 1.0194,  0.9184,  0.8449,  0.9643,  0.8449,  0.9643,  0.9276],
        [ 1.0286,  0.9092,  0.8908,  0.9276,  0.8449,  1.0194,  0.9092],
        [ 0.8449,  1.0102,  1.0745,  0.9643,  1.0561,  0.9092,  1.0102],
        [ 0.9276,  1.0653,  1.0286,  1.0469,  1.0010,  1.0653,  1.0469]])

用 mean=0, var=1 的正态分布随机初始化一个tensor:



In [9]:
a = torch.randn(5, 7)
print(a)
print(a.size())

tensor([[-1.6968,  1.0118, -1.3871,  0.9438,  1.3532,  0.5870, -0.8632],
        [-1.0935,  0.0820, -1.3389, -1.7860, -0.2920, -2.1959,  0.6514],
        [ 0.7380,  0.4910,  1.4724,  0.6694, -1.5204,  1.1456, -0.1136],
        [ 0.0470,  0.8175, -0.7787, -2.1541,  0.6594,  0.3566,  1.0292],
        [-2.4749,  0.9229,  0.3409,  1.3305,  0.0615,  1.3712,  0.7016]])
torch.Size([5, 7])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` 实际上是一个 tuple, 因此它支持相同的操作</p></div>

Inplace / Out-of-place
----------------------

第一个不同点在于 tensor 上的所有操作, 如果想要在 tensor 自身上进行的操作
(in-place) 就要加上一个 ``_`` 作为后缀. 例如, ``add`` 是一个 out-of-place
的 version ,而 ``add_`` 是一个 in-place 的 version .



In [10]:
a.fill_(3.5)
# a 的值现在变为 3.5

b = a.add(4.0)
# a 的值仍然是 3.5
# 返回的值 3.5 + 4.0 = 7.5 将作为b的值. 

print(a, b)

tensor([[ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000]]) tensor([[ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000]])


还有一些像 ``narrow`` 的操作是没有 in-place version , 所以也就不存在 ``.narrow_``
. 同样的, 也有像 ``fill_`` 的一些操作没有 out-of-place version . 因此, ``.fill``
也同样不存在.

Zero Indexing (零索引)
------------------------

Tensors 是 zero-indexed (索引从零开始)这是另外一个不同点. (在 lua 中, tensors 是
one-indexed (索引从一开始))



In [11]:
b = a[0, 3]  # 从 a 中选择第一行第四列的值.

Tensors 也可以用 Python 的切片索引



In [12]:
b = a[:, 3:5]  # 从 a 中选择所有行中第四列和第五列的值.

No camel casing
---------------

接下来一个小的不同是所有的函数都不是 camelCase 了. 
例如 ``indexAdd`` 现在被称为 ``index_add_``



In [36]:
x = torch.ones(5, 5)
print(x)

tensor([[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])


In [15]:
z = torch.Tensor(5, 2)
z[:, 0] = 10
z[:, 1] = 100
print(z)

tensor([[  10.,  100.],
        [  10.,  100.],
        [  10.,  100.],
        [  10.,  100.],
        [  10.,  100.]])


In [22]:
print(z ,'\n',x)

tensor([[  10.,  100.],
        [  10.,  100.],
        [  10.,  100.],
        [  10.,  100.],
        [  10.,  100.]]) 
 tensor([[ 101.,    1.,    1.,    1.,   11.],
        [ 101.,    1.,    1.,    1.,   11.],
        [ 101.,    1.,    1.,    1.,   11.],
        [ 101.,    1.,    1.,    1.,   11.],
        [ 101.,    1.,    1.,    1.,   11.]])


In [35]:
    >>> xtt = torch.ones(5, 3)
    >>> ttt = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
    >>> indextt = torch.tensor([0, 4, 2])
    >>> xtt.index_add_(0, indextt, ttt)

tensor([[  2.,   3.,   4.],
        [  1.,   1.,   1.],
        [  8.,   9.,  10.],
        [  1.,   1.,   1.],
        [  5.,   6.,   7.]])

In [58]:
x.index_add_(1, torch.LongTensor([4, 0]), z)
x

tensor([[ 601.,    1.,    1.,    1.,   61.],
        [ 601.,    1.,    1.,    1.,   61.],
        [ 601.,    1.,    1.,    1.,   61.],
        [ 601.,    1.,    1.,    1.,   61.],
        [ 601.,    1.,    1.,    1.,   61.]])

In [69]:
x.index_add_(0, torch.LongTensor([4, 0]), z.transpose(0,1))
print(x)

tensor([[ 801.,  201.,  201.,  201.,  261.],
        [ 601.,    1.,    1.,    1.,   61.],
        [ 601.,    1.,    1.,    1.,   61.],
        [ 611.,   11.,   11.,   11.,   71.],
        [ 611.,   11.,   11.,   11.,   71.]])


Numpy Bridge
------------

将 torch Tensor 转换为一个 numpy array, 反之亦然.
Torch Tensor 和 numpy array 将会共用底层的内存,
改变其中一个, 另外一个也会随之改变.

将 torch Tensor 转换为 numpy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [70]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [71]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [73]:
a.add_(1)
print(a)
print(b)

tensor([ 3.,  3.,  3.,  3.,  3.])
[3. 3. 3. 3. 3.]


将 numpy Array 转换为 torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [74]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)  # 看一下通过改变 np array 来自动的改变 torch Tensor

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


除了 CharTensor 之外, 所有 CPU 上的 Tensors 支持转变为 NumPy 并且
转换回来. 

CUDA Tensors
------------

CUDA Tensors 在 pytorch 中非常好用, 并且一个 CUDA tensor
从 CPU 转换到 GPU 仍将保持它底层的类型.



In [75]:
# 让我们在 CUDA 可用的时候运行这个单元
if torch.cuda.is_available():
    # 创建一个 LongTensor 并且将其转换使用 GPU
    # 的 torch.cuda.LongTensor 类型
    a = torch.LongTensor(10).fill_(3).cuda()
    print(type(a))
    b = a.cpu()
    # 将它转换到 CPU
    # 类型变回 torch.LongTensor