## sklearn 的数据预处理

In [1]:
import numpy as np
from sklearn import datasets
from sklearn import preprocessing
import pandas as pd

### 1.下载数据

In [2]:
d=datasets.load_iris()
x,y=d.data,d.target

In [3]:
testdata = pd.DataFrame({'pet': ['cat', 'dog', 'dog', 'fish'],                         
'age': [4 , 6, 3, 3],                         
'salary':[4, 5, 1, 2]})
testdata

age   pet  salary
0    4   cat       4
1    6   dog       5
2    3   dog       1
3    3  fish       2

### 2.预处理的类方法
    如果我想把这个类的东西应用到另一个数据上可以用类方法。

preprocessing.Binarizer 
preprocessing.FunctionTransformer
preprocessing.Imputer   #处理缺失数据
preprocessing.KernelCenterer#
preprocessing.LabelBinarizer#
preprocessing.LabelEncoder#
preprocessing.MaxAbsScaler#
preprocessing.MinMaxScaler##最大最小
preprocessing.MultiLabelBinarizer
preprocessing.Normalizer#规范
preprocessing.OneHotEncoder#onehot 编码
preprocessing.PolynomialFeatures  #多项式
preprocessing.RobustScaler#健壮的缩放
preprocessing.StandardScaler  #缩放

#### 2.1onehot 
    对数值编码，
    对字符串编码

In [144]:
testdata

age   pet  salary
0    4   cat       4
1    6   dog       5
2    3   dog       1
3    3  fish       2

In [4]:
#
preprocessing.OneHotEncoder(sparse = False).fit_transform(testdata.salary.values.reshape(-1,1))

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [5]:
#
preprocessing.OneHotEncoder(sparse = False).fit_transform(testdata.age.values.reshape(-1,1))

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [6]:
#同时对两个实现编码
preprocessing.OneHotEncoder(sparse = False).fit_transform( testdata[['age', 'salary']])

array([[0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0.]])

##### 查看编码结果信息

In [7]:
one=preprocessing.OneHotEncoder(sparse=False).fit(x)
one.fit_transform(x)

array([[0., 1., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [155]:
#查看每列对应的编码位置
one.feature_indices_

array([ 0,  8, 13, 20, 23], dtype=int32)

##### LabelBinarizer().fit_transform(testdata['pet'])

In [158]:
preprocessing.LabelBinarizer().fit_transform(testdata['pet'])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### LabelEncoder

In [166]:
label=preprocessing.LabelEncoder().fit_transform(testdata['pet'])

In [170]:
label

array([0, 1, 1, 2], dtype=int64)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
CountVectorizer

In [172]:
preprocessing.OneHotEncoder(sparse=False).fit_transform(label.reshape(-1,1))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 2.2标准正态缩放

In [20]:
scaler = preprocessing.StandardScaler().fit(x)
x_s=scaler.transform(x)
x_s.mean(),x_s.std()

(-1.3263464400855204e-15, 1.0)

#### 2.3缺失值的处理

In [66]:
imp=preprocessing.Imputer()
imp.fit(x)
np.all(imp.transform(x)==x)

True

#### 2.3多项式特征生成
$特征向量X从:math:(X_1, X_2) 被转换成:math:(1, X_1, X_2, X_1^2, X_1X_2, X_2^2)$

In [67]:
X = np.arange(6).reshape(3, 2)
poly = preprocessing.PolynomialFeatures(2)
poly.fit_transform(X)                             

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

#### 2.4装换器定制

In [88]:
t=preprocessing.FunctionTransformer(lambda x:np.abs(x))
t.transform(x)[1]

array([4.9, 3. , 1.4, 0.2])

### 3.预处理的函数方法
    scale 表示缩放

    preprocessing.add_dummy_feature 
    preprocessing.binarize  #设定一个阈值，二值，
    preprocessing.data 
    preprocessing.imputation 
    preprocessing.label   
    preprocessing.label_binarize #指定label，onehot
    preprocessing.maxabs_scale #用
    preprocessing.minmax_scale #指定最大最小值处理
    preprocessing.normalize   #规范
    preprocessing.robust_scale #健壮的缩放，处理异常值
    preprocessing.scale       #缩放

#### 3.1 scale

In [12]:
x_s=preprocessing.scale(x)
x_s.mean(),x_s.std()

(-1.3263464400855204e-15, 1.0)

In [31]:
preprocessing.minmax_scale?

#### 3.2 scale

In [32]:
x_s=preprocessing.minmax_scale(x,feature_range=(0, 1),axis=0)
x_s.min(),x_s.max()

(0.0, 1.0)

In [33]:
x_s.min(0)

array([0., 0., 0., 0.])

In [79]:
preprocessing.label_binarize(y,classes=(0,1,2))[:3]

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]])

#### 3.3

In [53]:
preprocessing.data.deprecated?

#### 3.4 normal
正则化的过程是将每个样本缩放到单位范数（每个样本的范数为1）

### 向量范数

#### 0,所有元素绝对值之和
$$\mid\mid x\mid\mid_1=\sum_{i=1}^{N}{x_i}$$

#### 2.平方和在开方
$$\mid \mid x\mid \mid_2=\sqrt{\sum_{i=1}^{N}{x_i^2}}$$

##### $\infty $ 所有元素中绝对值最大的值
##### $-\infty $ 所有元素中绝对值最小的值

#### p范数
$$\mid \mid x\mid \mid_p=(\sum_{i=1}^{N}{\mid x_i\mid^p})^{1/p}$$