1. lstm GRU:           http://blog.csdn.net/guotong1988/article/details/75045933
2. jupyter notebook:    http://blog.csdn.net/winnerineast/article/details/52274556

#### 一，  lstm
1. 忘记门
2. 新增门
3. 更新
4. 输出



#### 二， GRU
 

r(t) 负责决定h(t−1) 对new memory h^(t) 的重要性有多大， 如果r(t) 约等于0 的话，h(t−1) 就不会传递给new memory h^(t)

new memory

h^(t) 是对新的输入x(t) 和上一时刻的hidden state h(t−1) 的总结。计算总结出的新的向量h^(t) 包含上文信息和新的输入x(t).

Update gate

z(t) 负责决定传递多少ht−1给ht 。 如果z(t) 约等于1的话，ht−1 几乎会直接复制给ht ，相反，如果z(t) 约等于0， new memory h^(t) 直接传递给ht.

Hidden state:

h(t) 由 h(t−1) 和h^(t) 相加得到，两者的权重由update gate z(t) 控制。


$$ z_t = \sigma(W_z \text{x}_t + U_z \text{h}_{t-1})  $$
$$  r_t = \sigma(W_t \text{x}_t + U_t \text{h}_{t-1}) $$
$$ \widetilde{h}_t = \text{tanh}(W\text{x}_t + U(r_t \circ \text{h}_{t-1})) $$
$$ \text{h}_t = (1 - z_t) \circ \text{h}_{t-1} + z_t \circ \widetilde{h}_t $$

In [2]:
import tensorflow as tf
from tensorflow.contrib import rnn

x = tf.constant([[1]], dtype = tf.float32)

lstm_cell = rnn.BasicLSTMCell(2)
gru_cell = rnn.GRUCell(2)

state0_lstm = lstm_cell.zero_state(1,dtype=tf.float32)
output,state = lstm_cell(x,state0_lstm)

state0_gru = gru_cell.zero_state(1,dtype=tf.float32)
output2,state2 = gru_cell(x,state0_gru)

init = tf.global_variables
_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(output))
    print(sess.run(state))

    print(sess.run(output2))
    print(sess.run(state2))

[[-0.06551912  0.17653495]]
LSTMStateTuple(c=array([[-0.18371592,  0.29048127]], dtype=float32), h=array([[-0.06551912,  0.17653495]], dtype=float32))
[[-0.08273311 -0.28885445]]
[[-0.08273311 -0.28885445]]
